tasks:
  - command: pip3 install -U platformio==6.1.7 && platformio run -e tasmota

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
