on:
  workflow_dispatch:  # Manually start a workflow
  push:
    branches: development
    paths:
      - 'BUILDS.md'
      - 'I2CDEVICES.md'

jobs:

  copy_change:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push Builds.md and I2CDevices.md to https://github.com/Tasmota/docs
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'BUILDS.md,I2CDEVICES.md'
        destination_repo: 'Tasmota/docs'
        destination_branch: 'development'
        destination_folder: 'docs'
        user_email: 'github-actions@github.com'
        user_name: 'github-actions'
        commit_message: 'Builds.md or I2CDevices.md changed'
