name: Copy_firmware_master

on:
  push:
jobs:
  copycat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copycat tasmota
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: release-firmware/tasmota/.
          src_branch: master
          dst_path: ./firmware/release/.
          dst_owner: tasmota
          dst_branch: main
          dst_repo_name: install
          username: workflow
          commit_message: "Update from official release"

  copycat32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copycat tasmota32
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: release-firmware/tasmota32/.
          src_branch: master
          dst_path: ./firmware/release/.
          dst_owner: tasmota
          dst_branch: main
          dst_repo_name: install
          username: workflow
          commit_message: "Update from official release"
